tasks:
  - init: |
      touch /tmp/.npm-lock
      npm ci
      rm /tmp/.npm-lock
    command: npm run server
  - init: sleep 1 && while [ -f /tmp/.npm-lock ]; do sleep 1; done
  
image:
  file: .gitpod.dockerfile